---
######################################################
#
#        Install Dotfiles from Github
#
######################################################
# README:
#     Downloads Dotfiles from Git to ~/git/{Reponame}
#     Uses stow to symlink to ~/
#
#     use:  :%s/ to replace "aaa" with the username
#           fill in the variables in the set_fact section
#

#-----------------------------------------------------
#   Header & variablen
#
- name: dotfiles | load variables 
  tags: tag1,tag2
  set_fact:
    user_dir: "{{ replace_variable1 }}"
    user: "{{ replace_variable2 }}" 
    repo: "{{ replace_variable3 }}"

#-----------------------------------------------------
#   DEBUG
#
#- name: dotfiles | DEBUG - show loaded variables
#  tags: tag1,debug
#  debug:
#    msg: 
#      - "{{ user_dir }}"
#      - "{{ user }}"
#      - "{{ repo }}"


#-----------------------------------------------------
#   pre_tasks
#

- name: dotfiles | aaa | Ensure required packages are installed
  tags: tag1,tag2
  ansible.builtin.package:
    name:
      - git
      - stow
    state: present

- name: dotfiles | aaa | Remove existing files before stowing
  ansible.builtin.file:
    path: "{{ user_dir }}/{{ item }}"
    state: absent
  with_items:
    - .bashrc
    - .alacritty
    - .neofetch
    - .nvim
    - .tmux
    - .zsh

#-----------------------------------------------------
#   Main
#

- name: dotfiles | aaa | Create git directory in home folder
  tags: tag1,tag2
  ansible.builtin.file:
    path: "{{ user_dir }}/git"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"

- name: dotfiles | aaa | Clone dotfiles repository
  tags: tag1,tag2
  ansible.builtin.git:
    repo: "{{ repo }}"
    dest: '{{ user_dir }}/git/dotfiles-stow'
    update: yes

- name: dotfiles | aaa | Setze Besitzer und Gruppe für das geklonte Repository
  tags: tag1,tag2
  file:
    path: '{{ user_dir }}/git/dotfiles-stow'
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory

- name: dotfiles | aaa | Setze Besitzer und Gruppe für das geklonte Repository
  tags: tag1,tag2
  file:
    path: '{{ user_dir }}/.config'
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory

- name: dotfiles | aaa | Symlinks für Dotfiles erstellen
  tags: tag1,tag2
  command: "stow -d {{ user_dir }}/git/dotfiles-stow/ -t {{ user_dir }}/ bashrc alacritty neofetch nvim tmux zsh"
  args:
    chdir: "{{ user_dir }}/git/dotfiles-stow"


#-----------------------------------------------------
#   post_tasks
#


#-----------------------------------------------------
#   Handlers
#


#-----------------------------------------------------
#   roles
#






