---
######################################################
#
#     install docker ce complete
#
######################################################
# README:
#   installiert docker
#

#-----------------------------------------------------
#   Header & variablen
#
- name: docker | load variables 
  tags: docker,dockerce
  set_fact:
    user: "{{ architect_user }}"      #gets ownership and rights to files and mounts
    gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"   #"{{ var_2 }}"
    docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"    #"{{ var_3 }}"


#-----------------------------------------------------
#   DEBUG
#
- name: role_name | task_name
  tags: docker,dockerce,debug
  debug:
    msg: 
      - "{{ architect_user }}"

#-----------------------------------------------------
#   pre_tasks
#
- name: docker | Install required packages
  tags: docker,dockerce
  package:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

- name: docker | Add Docker’s official GPG key
  tags: docker,dockerce
  apt_key:
    url: "{{ gpg_key_url }}"
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  
- name: docker | Add Docker’s official GPG key - RHEL/CentOS
  tags: docker,dockerce
  rpm_key:
    url: "{{ gpg_key_url }}"
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: docker | Add Docker repository
  tags: docker,dockerce
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: docker | Add Docker repository - RHEL/CentOS
  tags: docker,dockerce
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

#-----------------------------------------------------
#   Main
#
- name: docker | Install Docker
  tags: docker,dockerce
  package:
    name: docker-ce
    state: latest
    update_cache: yes

- name: docker | Install pip
  tags: docker,dockerce
  package:
    name: python3-pip
    state: present
    update_cache: yes

- name: docker | Install pipx
  tags: docker,dockerce
  package:
    name: pipx
    state: present
    update_cache: yes

- name: docker | Install Docker-compose
  tags: docker,dockerce
  package:
    name: docker-compose
    state: latest
    update_cache: yes

      #- name: docker | Install Docker.io
      #  tags: docker,dockerce
      #  package:
      #    name: docker.io
      #    state: latest
      #    update_cache: yes


      #- name: docker | Install Docker Compose using pip
      #  tags: docker,dockerce
      #  community.general.pipx:
      #    name: docker-compose
      #    state: latest

#-----------------------------------------------------
#   post_tasks
#
- name: docker | Ensure Docker service is started
  tags: docker,dockerce
  service:
    name: docker
    state: started
    enabled: yes

- name: docker | Add user to Docker group
  tags: docker,dockerce
  user:
    name: "{{ user }}"
    groups: docker
    append: yes


#-----------------------------------------------------
#   Handlers
#


#-----------------------------------------------------
#   roles
#




