---
######################################################
#
#    mount a smb drive 
#
######################################################
# README:
#   creates a mountpoint and mounts a smb drive using variables
#
# usage:  define variables in var file and rename the architect_user... to those variables
#         rename tags & name

#-----------------------------------------------------
#   Header & variablen
#
- name: docker | load variables 
  tags: docker,smb-nas
  set_fact:
    user: "{{ architect_user }}"      #gets ownership and rights to files and mounts
    smb_cred_file: "{{ architect_user_dir }}/.smbcredentials"
    local_mountpoint: "{{ docker_host_local_nas_mount_point }}"
    remote_mountpoint: "{{ nas_path }}{{ ansible_role_name }}"

#-----------------------------------------------------
#   DEBUG
#
- name: docker | DEBUG show variables
  tags: docker,smb-nas,debug
  debug:
    msg:
      - "{{ user }} - {{ architect_user }}"
      - "{{ smb_cred_file }} - {{ architect_user_dir }}/.smbcredentials"
      - "{{ local_mountpoint }} - {{ docker_host_local_nas_mount_point }}"
      - "{{ remote_mountpoint }} - {{ nas_path }}{{ ansible_role_name }}"

#-----------------------------------------------------
#   pre_tasks
#
- name: docker | Install cifs-utils
  tags: docker,smb-nas
  ansible.builtin.package:
    name: cifs-utils
    state: present
#register: package_install_smb_nas  #alte reboot funktion ohne handler
  notify: handler | reboot

#-----------------------------------------------------
#   Main
#
- name: docker | Create smbcredentials file
  tags: docker,smb-nas
  ansible.builtin.template:
    src: templates/smbcredentials.j2
    dest: "{{ smb_cred_file }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0600"

- name: docker | Create mount directory
  tags: docker,smb-nas
  ansible.builtin.file:
    path: "{{ local_mountpoint }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: docker | Mount SMB share
  tags: docker,smb-nas
  ansible.builtin.mount:
    path: "{{ local_mountpoint }}"
    src: "//{{ remote_mountpoint }}"
    fstype: cifs
    opts: "credentials={{ smb_cred_file }},uid={{ user }},gid={{ user }},vers=3.0,iocharset=iso8859-1,_netdev"  
    state: mounted
  become: true


#-----------------------------------------------------
#   post_tasks
#
- name: docker | Ensure NAS mount is persistent across reboots
  tags: docker,smb-nas
  lineinfile:
    path: /etc/fstab
    line: "//{{ remote_mountpoint }} {{ local_mountpoint }} cifs credentials={{ smb_cred_file }},uid={{ user }},gid={{ user }},vers=3.0,iocharset=iso8859-1,_netdev 0 0"
    state: present
  become: yes


#-----------------------------------------------------
#   Handlers
#


#-----------------------------------------------------
#   roles
#




